- name: Configuración de Nginx
  hosts: server1
  become: yes

  tasks:
    - name: Instalar epel-release
      yum:
        name: epel-release
        state: present

    - name: Instalar nginx
      yum:
        name: nginx
        state: present

    - name: Iniciar Nginx
      service:
        name: nginx
        state: started

    - name: Crear archivo index.html.j2
      template:
        src: templates/index.html.j2
        dest: /usr/share/nginx/html/index.html

    - name: start firewalld
      service:
        name: firewalld
        state: started
        enabled: yes
      become: yes

    - name: enable 8080
      firewalld:
        zone: public
        port: 8080/tcp
        permanent: true
        state: enabled
      become: yes

    - name: Recargar la configuración del firewall
      command: firewall-cmd --reload
      
    - name: Reiniciar Nginx
      service:
        name: nginx
        state: restarted

~    