- name: Instalar Python, Django, pip3, boto3 y Git
  hosts: servers  # Nombre del grupo de servidores a los que se aplicarán las tareas
  become: yes  # Indica que las tareas se ejecutarán como superusuario (sudo)

  tasks:
    - name: Instalar Python 3 y pip3
      yum:  # Utiliza el módulo "yum" para gestionar paquetes en sistemas CentOS
        name:
          - python3  # Lista de paquetes a instalar, en este caso Python 3
          - python3-pip  # También instalamos pip3
      when: ansible_distribution == "CentOS"  # Condición para ejecutar esta tarea solo en sistemas CentOS

    - name: Instalar Git
      package:  # Utiliza el módulo "package" para gestionar paquetes
        name: git  # Instala el paquete "git"
      when: ansible_distribution == "CentOS"  # Condición para ejecutar esta tarea solo en sistemas CentOS

    - name: Instalar Django y boto3 con pip3
      pip:  # Utiliza el módulo "pip" para instalar paquetes de Python
       executable: /usr/bin/pip3  # Ruta al ejecutable de pip3 en el sistema
       name:
          - Django  # Instala el paquete Django
          - boto3  # Instala el paquete boto3
      become: yes  # Ejecuta la tarea como superusuario (sudo)
